export const START_FETCH_VEHICLES = 'START_FETCH_VEHICLES';
export const FETCH_VEHICLES_SUCCESS = 'FETCH_VEHICLES_SUCCESS';
export const FETCH_VEHICLES_ERROR = 'FETCH_VEHICLES_ERROR';
export const START_ADD_VEHICLE = 'START_ADD_VEHICLE';
export const ADD_VEHICLE = 'ADD_VEHICLE';
export const ADD_VEHICLE_ERROR = 'ADD_VEHICLE_ERROR';

export const CHANGE_NAME = 'CHANGE_NAME'
export const CHANGE_CONTACT = 'CHANGE_CONTACT'
export const CHANGE_EMAIL = 'CHANGE_EMAIL'
export const CHANGE_CITY = 'CHANGE_CITY'
export const CHANGE_VEHICLE_TYPE = 'CHANGE_VEHICLE_TYPE'
export const CHANGE_GEAR = 'CHANGE_GEAR'
export const CHANGE_WHEEL_DRIVE = 'CHANGE_WHEEL_DRIVE'
export const CHANGE_FUEL = 'CHANGE_FUEL'
export const CHANGE_SEATERS = 'CHANGE_SEATERS'
export const CHANGE_VEHICLE_REGISTRATION = 'CHANGE_VEHICLE_REGISTRATION'
export const CHANGE_VEHICLE_BRAND = 'CHANGE_VEHICLE_BRAND'
export const CHANGE_VEHICLE_MODEL = 'CHANGE_VEHICLE_MODEL'
export const CHANGE_VEHICLE_MAKE = 'CHANGE_VEHICLE_MAKE'
export const CHANGE_COMMENT = 'CHANGE_COMMENT'
export const CHANGE_PICTURESRC1 = 'CHANGE_PICTURESRC1'
export const CHANGE_PICTURESRC2 = 'CHANGE_PICTURESRC2'
export const CHANGE_PICTURESRC3 = 'CHANGE_PICTURESRC3'
export const CHANGE_PICTURESRC4 = 'CHANGE_PICTURESRC4'
export const CHANGE_PICTURESRC5 = 'CHANGE_PICTURESRC5'
export const CREATE_VEHICLE_ID = 'CREATE_VEHICLE_ID'

export const CHANGE_LOGIN_EMAIL = 'CHANGE_LOGIN_EMAIL'
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD'

export const CHANGE_SIGNUP_NAME = 'CHANGE_SIGNUP_NAME'
export const CHANGE_SIGNUP_CONTACT = 'CHANGE_SIGNUP_CONTACT'
export const CHANGE_SIGNUP_EMAIL = 'CHANGE_SIGNUP_EMAIL'
export const CHANGE_SIGNUP_ADDRESS = 'CHANGE_SIGNUP_ADDRESS'
export const CHANGE_SIGNUP_PASSWORD = 'CHANGE_SIGNUP_PASSWORD'
export const CHANGE_SIGNUP_CONFIRM_PASSWORD = 'CHANGE_SIGNUP_CONFIRM_PASSWORD'
export const START_SIGNUP = 'START_SIGNUP'
export const COMPLETE_SIGNUP = 'COMPLETE_SIGNUP'
export const ERROR_SIGNUP = 'ERROR_SIGNUP'
export const START_LOGIN = 'START_LOGIN'
export const COMPLETE_LOGIN = 'COMPLETE_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'
export const WRONG_PASSWORD = 'WRONG_PASSWORD'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const VOID_USER = 'VOID_USER'

export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

